import { Box, Container } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { DraftJsEditor } from '../components/draftJs/DraftJsEditor/DraftJsEditor'
import { ReactQuillEditor } from '../components/reactQuill/ReactQuillEditor/ReactQuillEditor'

const Home: NextPage = () => {
  // ページ読み込みが完了したか
  const [isLoaded, setIsLoaded] = useState<boolean>(false)

  // 初期化処理
  useEffect(() => {
    // ページ読み込み完了状態にする
    setIsLoaded(true)
  }, [])

  return (
    <>
      <Head>
        <title>wysiwyg with NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{display: isLoaded ? undefined: "none"}}>
        <Container maxWidth="xl" component={'main'}>
          <Box component={'section'} sx={{my: 2}}>
            <DraftJsEditor></DraftJsEditor>
          </Box>
          <Box component={'section'} sx={{my: 2}}>
            <ReactQuillEditor></ReactQuillEditor>
          </Box>
        </Container>
      </Box>
    </>
  )
}

export default Home
