import { Box, Container } from '@mui/material'
import { Editor, EditorState, RichUtils } from 'draft-js'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import 'draft-js/dist/Draft.css';

const Home: NextPage = () => {
  // ページ読み込みが完了したか
  const [isLoaded, setIsLoaded] = useState<boolean>(false)
  
  const [editorState, setEditorState] = useState(() => EditorState.createEmpty())

  // 初期化処理
  useEffect(() => {
    // ページ読み込み完了状態にする
    setIsLoaded(true)
  }, [])

  function _onBoldClick() {
    setEditorState(RichUtils.toggleInlineStyle(editorState, 'BOLD'));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{display: isLoaded ? undefined: "none"}}>
        <Container maxWidth="xl" component={'main'}>
          {isLoaded && (
            <>
            <button onClick={_onBoldClick.bind(this)}>Bold</button>
            <Editor 
            editorKey="test-key"
            placeholder="Write something!"
            editorState={editorState} 
            onChange={setEditorState}/>
            </>
          )}
        </Container>
      </Box>
    </>
  )
}

export default Home
